# Generated by Django 5.1.5 on 2025-02-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_blog_published_at_alter_blog_cover_image_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Area of Practice')),
                ('icon', models.CharField(help_text="Font Awesome icon class, e.g., 'fa-scale-balanced'", max_length=50)),
                ('detailed_description', models.TextField(verbose_name='Detailed Description')),
                ('slug', models.SlugField(help_text='URL-friendly name for the practice area', unique=True)),
            ],
        ),
    ]
