# Generated by Django 5.1.5 on 2025-02-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(blank=True, default='default_cover.jpg', null=True, upload_to='blog_covers/'),
        ),
    ]
