# Generated by Django 5.1.5 on 2025-02-18 17:04

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_blog_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='detailed_description',
            field=tinymce.models.HTMLField(verbose_name='Detailed Description'),
        ),
    ]
