# Generated by Django 5.1.5 on 2025-02-17 10:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_blog_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='detailed_description',
            field=ckeditor.fields.RichTextField(verbose_name='Detailed Description'),
        ),
    ]
