# Generated by Django 5.1.5 on 2025-03-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicearea',
            name='icon',
        ),
        migrations.AddField(
            model_name='practicearea',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image representing the practice area', null=True, upload_to='practice_areas/'),
        ),
    ]
