# Generated by Django 5.1.5 on 2025-03-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_practicearea_icon_practicearea_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
